# Remote theme directory
remote_theme: analytics-link/analytics-link.github.io

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme

#-------------------------------
# General Site Settings
title: Irène Aimée Mugeni
description: "Hi, I’m Irène, a recent MSBA graduate from Carnegie Mellon University with training across machine learning, statistical modeling, optimization, and data-driven decision-making. My portfolio highlights projects where I apply these tools to generate measurable business impact. Feel free to explore my GitHub and LinkedIn using the links below!"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# About Section
subtitle: Data Science/Business Analytics <span style="color:#219781">Portfolio</span>
location: "Pittsburgh, PA"
avatar_image: /img/IMG_0764 Cropped.jpg

#-------------------------------
# Contact links
linkedln: "https://www.linkedin.com/in/irene-mugeni//#" # Add your linkedln handle
github: "https://github.com/MugeniAI05/#"  # Add your github handle

paginate: 6
paginate_path: "/page/:num"

sass:
  sass_dir: _sass
  style: compressed # possible values: nested expanded compact compressed

defaults:
  - scope:
      type: posts
    values:
      layout: post
      read_time: true
      share: false


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/










